/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkel4;

import javax.swing.JOptionPane;

/**
 *
 * @author A S U S
 */
public class HomeMenu extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeMenu(String _username) {
        initComponents();
        lblWelcome.setText("Welcome to," + _username);
    }

    private HomeMenu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        txtNama = new javax.swing.JTextField();
        txtMeja = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbEspresso = new javax.swing.JCheckBox();
        cbAmericano = new javax.swing.JCheckBox();
        cbCappucino = new javax.swing.JCheckBox();
        cbLatte = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaCappucino = new javax.swing.JTextField();
        hargaAmericano = new javax.swing.JTextField();
        hargaespresso = new javax.swing.JTextField();
        hargaLatte = new javax.swing.JTextField();
        jumlahCappucino = new javax.swing.JTextField();
        jumlahAmericano = new javax.swing.JTextField();
        jumlahEspresso = new javax.swing.JTextField();
        jumlahLatte = new javax.swing.JTextField();
        totalCappucino = new javax.swing.JTextField();
        totalAmericano = new javax.swing.JTextField();
        totalEspresso = new javax.swing.JTextField();
        totalLatte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalfull = new javax.swing.JTextField();
        cbRotibakar = new javax.swing.JCheckBox();
        cbPisangbakar = new javax.swing.JCheckBox();
        cbDonat = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jumlahRotibakar = new javax.swing.JTextField();
        jumlahPisangbakar = new javax.swing.JTextField();
        jumlahDonat = new javax.swing.JTextField();
        totalRotibakar = new javax.swing.JTextField();
        totalPisangbakar = new javax.swing.JTextField();
        totalDonat = new javax.swing.JTextField();
        checkout = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        hargaDonat = new javax.swing.JTextField();
        hargaPisangbakar = new javax.swing.JTextField();
        hargaRotibakar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel3.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N
        jLabel3.setText("Menu");

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        lblWelcome.setFont(new java.awt.Font("STXihei", 1, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome to ,");

        btnLogout.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnLogout))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setText("Jumlah");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Harga");

        cbEspresso.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbEspresso.setText("Espresso");
        cbEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspressoActionPerformed(evt);
            }
        });

        cbAmericano.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbAmericano.setText("Americano");
        cbAmericano.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbAmericanoStateChanged(evt);
            }
        });

        cbCappucino.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbCappucino.setText("Cappucino");
        cbCappucino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCappucinoStateChanged(evt);
            }
        });

        cbLatte.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbLatte.setText("Latte");
        cbLatte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbLatteStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("Pilih Menu");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setText("Sub Total");

        hargaCappucino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaCappucino.setText("0");

        hargaAmericano.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaAmericano.setText("0");

        hargaespresso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaespresso.setText("0");

        hargaLatte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaLatte.setText("0");

        jumlahCappucino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahCappucino.setText("0");

        jumlahAmericano.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahAmericano.setText("0");

        jumlahEspresso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahEspresso.setText("0");

        jumlahLatte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahLatte.setText("0");

        totalCappucino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalCappucino.setText("0");

        totalAmericano.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalAmericano.setText("0");

        totalEspresso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalEspresso.setText("0");

        totalLatte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalLatte.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel6.setText("Total ");

        diskon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diskon.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel7.setText("Total Bayar");

        bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bayar.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel8.setText("Diskon");

        totalfull.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalfull.setText("0");

        cbRotibakar.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbRotibakar.setText("Roti Bakar");
        cbRotibakar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbRotibakarStateChanged(evt);
            }
        });

        cbPisangbakar.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbPisangbakar.setText("Pisang Bakar ");
        cbPisangbakar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbPisangbakarStateChanged(evt);
            }
        });

        cbDonat.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        cbDonat.setText("Donat");
        cbDonat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbDonatStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel9.setText("Minuman");

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel10.setText("Makanan");

        jumlahRotibakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahRotibakar.setText("0");

        jumlahPisangbakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahPisangbakar.setText("0");
        jumlahPisangbakar.setToolTipText("");

        jumlahDonat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahDonat.setText("0");

        totalRotibakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalRotibakar.setText("0");

        totalPisangbakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPisangbakar.setText("0");

        totalDonat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalDonat.setText("0");

        checkout.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N
        checkout.setText("CHECK OUT");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N
        btnHapus.setText("Clear");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        hargaDonat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaDonat.setText("0");

        hargaPisangbakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaPisangbakar.setText("0");

        hargaRotibakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaRotibakar.setText("0");
        hargaRotibakar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbDonat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbPisangbakar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbRotibakar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(92, 92, 92)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(hargaAmericano, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaLatte, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaCappucino, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaespresso, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaPisangbakar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaDonat, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaRotibakar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jumlahCappucino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jumlahRotibakar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlahPisangbakar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlahDonat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlahAmericano, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlahLatte, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlahEspresso, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkout)
                                .addGap(162, 162, 162))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalAmericano, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(totalCappucino)
                            .addComponent(totalEspresso)
                            .addComponent(totalLatte)
                            .addComponent(diskon)
                            .addComponent(totalfull)
                            .addComponent(bayar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalDonat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalPisangbakar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalRotibakar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRotibakar)
                            .addComponent(hargaRotibakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahRotibakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalRotibakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbPisangbakar)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jumlahPisangbakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalPisangbakar)
                                .addComponent(hargaPisangbakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(cbDonat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahDonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCappucino)
                            .addComponent(totalCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAmericano)
                            .addComponent(hargaAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEspresso)
                            .addComponent(hargaespresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahLatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLatte)
                            .addComponent(hargaLatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkout)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cbEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspressoActionPerformed
        // TODO add your handling code here:
             if (cbEspresso.isSelected()){
            hargaespresso.setEnabled(true);
            jumlahEspresso.setEnabled(true);           
            totalEspresso.setEnabled(true);
        }else{
            hargaespresso.setEnabled(false);
            jumlahEspresso.setEnabled(false);
            totalEspresso.setEnabled(false);
             }

    }//GEN-LAST:event_cbEspressoActionPerformed
         
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,"Apakah anda yakin ingin Logout?","Konfirmasi", JOptionPane.YES_NO_OPTION);
       // 0 = yes, 1 = no, 2 = cancel
       
       if (input == 0){
           LoginMenu lm = new LoginMenu();
           lm.setLocationRelativeTo(null);
           lm.setVisible(true);
           this.setVisible(false);
       }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void cbCappucinoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCappucinoStateChanged
        // TODO add your handling code here:
        if (cbCappucino.isSelected()){
            hargaCappucino.setEnabled(true);
            jumlahCappucino.setEnabled(true);           
            totalCappucino.setEnabled(true);
        }else{
            hargaCappucino.setEnabled(false);
            jumlahCappucino.setEnabled(false);
            totalCappucino.setEnabled(false);
        }
    }//GEN-LAST:event_cbCappucinoStateChanged

    private void cbAmericanoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbAmericanoStateChanged
        // TODO add your handling code here:
        if (cbAmericano.isSelected()){
            hargaAmericano.setEnabled(true);
            jumlahAmericano.setEnabled(true);           
            totalAmericano.setEnabled(true);
        }else{
            hargaAmericano.setEnabled(false);
            jumlahAmericano.setEnabled(false);
            totalAmericano.setEnabled(false);
        }
    }//GEN-LAST:event_cbAmericanoStateChanged

    private void cbLatteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbLatteStateChanged
        // TODO add your handling code here:
        if (cbLatte.isSelected()){
            hargaLatte.setEnabled(true);
            jumlahLatte.setEnabled(true);           
            totalLatte.setEnabled(true);
        }else{
            hargaLatte.setEnabled(false);
            jumlahLatte.setEnabled(false);
            totalLatte .setEnabled(false);
        }
    }//GEN-LAST:event_cbLatteStateChanged

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        //Untuk menghitung cappucino
        int harga = Integer.parseInt(hargaCappucino.getText());
        int jumlah = Integer.parseInt(jumlahCappucino.getText());
        totalCappucino.setText(Integer.toString(jumlah * harga)); 
        // Untuk menghitung Americano
        int harga1 = Integer.parseInt(hargaAmericano.getText());
        int jumlah1= Integer.parseInt(jumlahAmericano.getText());
        totalAmericano.setText(Integer.toString(harga1 * jumlah1));
        // Untuk menghitung Espresso
        int harga2 = Integer.parseInt(hargaespresso.getText());
        int jumlah2 = Integer.parseInt(jumlahEspresso.getText());
        totalEspresso.setText(Integer.toString(harga2 * jumlah2)); 
        // Untuk menghitung Latte
        int harga3 = Integer.parseInt(hargaLatte.getText());
        int jumlah3 = Integer.parseInt(jumlahLatte.getText());
        totalLatte.setText(Integer.toString(harga3 * jumlah3)); 
        // Untuk menghitung Rotibakar
        int harga4 = Integer.parseInt(hargaRotibakar.getText());
        int jumlah4 = Integer.parseInt(jumlahRotibakar.getText());
        totalRotibakar.setText(Integer.toString(harga4 * jumlah4));
        //Untuk menghitung pisang bakar
        int harga5 = Integer.parseInt(hargaPisangbakar.getText());
        int jumlah5 = Integer.parseInt(jumlahPisangbakar.getText());
        totalPisangbakar.setText(Integer.toString(harga5 * jumlah5));
        // Untuk menghitung Donat
        int harga6 = Integer.parseInt(hargaDonat.getText());
        int jumlah6 = Integer.parseInt(jumlahDonat.getText());
        totalDonat.setText(Integer.toString(harga6 * jumlah6));
        
        // Menghitung harga total, diskon dan total bayar
        int Total1 = Integer.parseInt(totalCappucino.getText());
        int Total2 = Integer.parseInt(totalAmericano.getText());
        int Total3 = Integer.parseInt(totalEspresso.getText());
        int Total4 = Integer.parseInt(totalLatte.getText());
        int Total5 = Integer.parseInt(totalRotibakar.getText());
        int Total6 = Integer.parseInt(totalPisangbakar.getText());
        int Total7 = Integer.parseInt(totalDonat.getText());
        int total = Total1 + Total2 + Total3 + Total4+Total5+Total6+Total7;
        diskon.setText("Rp." + total + ",00");
        if (total > 200000){
            totalfull.setText("20%");
            total = total-(total * 20/100);
            bayar.setText("Rp." + total + ",00");
        }else if (total > 100000){
            totalfull.setText("10%");
            total = total-(total*10/100);
            bayar.setText("Rp." + total + ",00");
        }else{
            bayar.setText("Rp."+total+",00");
        }
        
    }//GEN-LAST:event_checkoutActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        hargaCappucino.setText("");
        jumlahCappucino.setText("");
        totalCappucino.setText("");
        hargaAmericano.setText("");
        jumlahAmericano.setText("");
        totalAmericano.setText("");
        hargaLatte.setText("");
        jumlahLatte.setText("");
        totalLatte.setText("");
        hargaespresso.setText("");
        jumlahEspresso.setText("");           
        totalEspresso.setText("");
        hargaRotibakar.setText("");
        jumlahRotibakar.setText("");          
        totalRotibakar.setText("");
        hargaPisangbakar.setText("");
        jumlahPisangbakar.setText("");          
        totalPisangbakar.setText("");
        hargaDonat.setText("");
        jumlahDonat.setText("");           
        totalDonat.setText("");
        totalfull.setText("");
        diskon.setText("");
        bayar.setText("");
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cbRotibakarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbRotibakarStateChanged
        // TODO add your handling code here:
          if (cbRotibakar.isSelected()){
            hargaRotibakar.setEnabled(true);
            jumlahRotibakar.setEnabled(true);           
            totalRotibakar.setEnabled(true);
        }else{
            hargaRotibakar.setEnabled(false);
            jumlahRotibakar.setEnabled(false);
            totalRotibakar.setEnabled(false);
        }
    }//GEN-LAST:event_cbRotibakarStateChanged

    private void cbPisangbakarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPisangbakarStateChanged
        // TODO add your handling code here:
          if (cbPisangbakar.isSelected()){
            hargaPisangbakar.setEnabled(true);
            jumlahPisangbakar.setEnabled(true);           
            totalPisangbakar.setEnabled(true);
        }else{
            hargaPisangbakar.setEnabled(false);
            jumlahPisangbakar.setEnabled(false);
            totalPisangbakar.setEnabled(false);
        }
    }//GEN-LAST:event_cbPisangbakarStateChanged

    private void cbDonatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbDonatStateChanged
        // TODO add your handling code here:
        if (cbDonat.isSelected()){
            hargaDonat.setEnabled(true);
            jumlahDonat.setEnabled(true);           
            totalDonat.setEnabled(true);
        }else{
            hargaDonat.setEnabled(false);
            jumlahDonat.setEnabled(false);
            totalDonat.setEnabled(false);
        }
    }//GEN-LAST:event_cbDonatStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String [] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JCheckBox cbAmericano;
    private javax.swing.JCheckBox cbCappucino;
    private javax.swing.JCheckBox cbDonat;
    private javax.swing.JCheckBox cbEspresso;
    private javax.swing.JCheckBox cbLatte;
    private javax.swing.JCheckBox cbPisangbakar;
    private javax.swing.JCheckBox cbRotibakar;
    private javax.swing.JButton checkout;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField hargaAmericano;
    private javax.swing.JTextField hargaCappucino;
    private javax.swing.JTextField hargaDonat;
    private javax.swing.JTextField hargaLatte;
    private javax.swing.JTextField hargaPisangbakar;
    private javax.swing.JTextField hargaRotibakar;
    private javax.swing.JTextField hargaespresso;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumlahAmericano;
    private javax.swing.JTextField jumlahCappucino;
    private javax.swing.JTextField jumlahDonat;
    private javax.swing.JTextField jumlahEspresso;
    private javax.swing.JTextField jumlahLatte;
    private javax.swing.JTextField jumlahPisangbakar;
    private javax.swing.JTextField jumlahRotibakar;
    private javax.swing.JLabel lblWelcome;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JTextField totalAmericano;
    private javax.swing.JTextField totalCappucino;
    private javax.swing.JTextField totalDonat;
    private javax.swing.JTextField totalEspresso;
    private javax.swing.JTextField totalLatte;
    private javax.swing.JTextField totalPisangbakar;
    private javax.swing.JTextField totalRotibakar;
    private javax.swing.JTextField totalfull;
    private javax.swing.JTextField txtMeja;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
